spring:
  redis:
    host: localhost
    port: 6379
---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://database-1.ciyih17rti9c.ap-northeast-2.rds.amazonaws.com:13306/StackOverFlow?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
config:
  domain: http://team28-pre-bucket.s3-website.ap-northeast-2.amazonaws.com